### ISSUE TITLE
Provide a more specific Activation event

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#10]
currently it is always activated.

https://github.com/jboss-fuse/vscode-datavirt/blob/3c73b7a7410f1d5c6893f75b74d9cd0c613df46f/package.json#L133-L135

I think it can be nice to restrain to:
- yaml file in workspace
- one of the provided commands called
- some other?

**Comment by lhein** [comment]
Please create a FUSETOOLS2 issue for this.

**Comment by apupier** [comment]
moved to JIRA https://issues.redhat.com/browse/FUSETOOLS2-387
