### ISSUE TITLE
dirty editor doesn't warn about data loss when being closed

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#102]
when closing the ddl editor without saving, there is no warning that changes will be ignored

**Comment by apupier** [comment]
please create related JIRA isseu in FUSETOOLS2 project as we agreed durign team meeting. it allows to give more visibility to everyone, especially for QE team.

**Comment by apupier** [comment]
moved to https://issues.redhat.com/browse/FUSETOOLS2-336
