### ISSUE TITLE
new datasource entry creation validation improvements

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#105]
** Wrong validation for data source entry:
*** it is forbidding to use _ (by default there is one created with name SPRING_TEIID_DATA_MONGODB_MYDATASOURCE_REMOTE_SERVER_LIST so with key REMOTE_SERVER_LIST)
*** it is forbidding names lower than 4 but in examples there is SSL which is 3
*** it is not checking for same key name with uppercase which is what needs to be checked as the value is transformed and uppercased right after. An error notification is provided when finishing the command

**Comment by apupier** [comment]
please create related JIRA isseu in FUSETOOLS2 project as we agreed durign team meeting. it allows to give more visibility to everyone, especially for QE team.

**Comment by lhein** [comment]
linked to #106

**Comment by apupier** [comment]
why is it closed?
if implemented can you link the PR?

**Comment by lhein** [comment]
It is closed because we agreed to use FUSETOOLS2 Jira as our issue system.

**Comment by apupier** [comment]
cool. Can you link the related issue?

**Comment by lhein** [comment]
FUSETOOLS2-329
