### ISSUE TITLE
creation / validation improvements for environment variables

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#106]
With the change of the datasource format (#111) this will become more related to environment variable definitions because the datasources functionality will be reimplemented for this.

For the environment variables we need to have validation improvements too:
- clarify if environment variable names have special rules for naming
- check if a variable with the same name exists already
- clarify if a global environment variable could be empty string and adapt code accordingly
- when hitting escape when asked for a name there is currently an error notification which should be removed

**Comment by apupier** [comment]
please create related JIRA isseu in FUSETOOLS2 project as we agreed durign team meeting. it allows to give more visibility to everyone, especially for QE team.

**Comment by apupier** [comment]
moved to JIRA https://issues.redhat.com/browse/FUSETOOLS2-332
