### ISSUE TITLE
The VDB name doesn't need to be uppercase

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#112]
- don't uppercase the VDB name when replacing the placeholders in the ddl
- allow also capital letters in the vdb name

**Comment by apupier** [comment]
please create related JIRA isseu in FUSETOOLS2 project as we agreed durign team meeting. it allows to give more visibility to everyone, especially for QE team.

**Comment by rareddy** [comment]
@apupier instead of FUSETOOLS do you want to use TEIIDTOOLS project? So that we can keep them in single place. I can create whatever categories and labels for these?

**Comment by apupier** [comment]
it will require that we update our dashboard to include also the TEIIDTOOLS project and see how to match the different state. This woudl need to be discussed with our QE Team too.

I don' tunderstand hwy you say that using TEIIDTOOLS will keep them in a single place. You are also creating issues for VS Code DataVirt in TEIIDTools? The Teiid Tool is plannign to work on the VS Code Data Virtualization extension?

**Comment by lhein** [comment]
Actually this vs code plugin is actively developed and maintained by the Fuse Tools team (at least for a foreseeable future) which led to the decision to have its ticket managed in our Jira project. Maybe we should discuss that with Paolo if you feel that this is not a good situation, Ramesh. Tbh I have no strong opinion on that. We just need to ensure that our QE team knows where the issues are as long as you don't bring in your own QE people.

**Comment by rareddy** [comment]
>it will require that we update our dashboard to include also the TEIIDTOOLS project and see how  > match the different state

yes, that is true. I agree it is more work that way

> This woudl need to be discussed with our QE Team too.

QE typically looks at the ENTESB (at least AFAIK)

> I don' tunderstand hwy you say that using TEIIDTOOLS will keep them in a single place. 

All Teiid tools related stuff is there.

> You are also creating issues for VS Code DataVirt in TEIIDTools? 

No, so far you were just using github issues day to day, and we used ENTESB for tracking at QE and management. Now we are adding a third one.

> The Teiid Tool team is planning to work on the VS Code Data Virtualization extension?

No, our team does not have any bandwidth currently for participating. What I am advocating is, instead of making a decision based on the team building maybe consider based on technology it supports?

I can certainly add FUSETOOLS with this component to DashBoard as I already manage 4 others here https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=4173&projectKey=TEIIDTOOLS but making a suggestion if it better to use on that something more closely aligned with Teiid stuff. B

**Comment by apupier** [comment]
> > This woudl need to be discussed with our QE Team too.
> 
> QE typically looks at the ENTESB (at least AFAIK)

there is a dedicated Fuse Tooling QE Team which is looking to FUSETOOLS and FUSETOOLS2

**Comment by rareddy** [comment]
Ok, I can always pull in from FUSETOOLS2, then

**Comment by apupier** [comment]
> but making a suggestion if it better to use on that something more closely aligned with Teiid stuff. B

understand the concern

> Ok, I can always pull in from FUSETOOLS2, then

thanks. at least in a first time, I think it will be easier.

it makes sense discuss moving to TEIIDTOOLS. We need to synchronize with QE and Doc to see if and how we can move to TEIIDTOOLS for VS Code Data Virtualization.

**Comment by lhein** [comment]
Guys, I really don't want to interrupt your discussion but I think it doesn't belong here. Can we take that to the appropriate chat channel instead or create a mail thread?

**Comment by apupier** [comment]
I think we need to sort out what is the right rule.
in [DV Use case](https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.d9goxmxbmbt0), it is mentioned:
`This name must conform to an Openshift resource name.`
OpenShift resource name have the following constraints (see `[here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)`):
- contain no more than 253 characters
- contain only lowercase alphanumeric characters, ‘-’ or ‘.’
- start with an alphanumeric character
- end with an alphanumeric character

this is not compatible with uppercased letters as proposed here

**Comment by lhein** [comment]
I have seen an example where it had mixed lower and upper case letters in the name. Unfortunately I can't find that example atm and it could have been just an error in that example too. I will reach out to Ramesh for clarification.

**Comment by lhein** [comment]
Closing as rejected. We stick to the rules of OpenShift resource naming.
