### ISSUE TITLE
yaml files are only parsed in the root folder

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#2]
we need to define whether to look in all subfolders recursively or if there is a specific place to expect those yaml file to reside.

**Comment by apupier** [comment]
@rareddy is there a specific layout of projects using the "vdb" yaml files? or they can be in whatever folder?

**Comment by rareddy** [comment]
@apupier right now it is a singular YAML file, which is deployed using Operator. I suppose it could be any folder. 

Earlier I did wanted to split the DDL content into multiple files and stitch them at the end into a single file, especially representing each source separately and able to autogenerate some DDL code, but didn't go that route as that would require us to write a parser for DDL if we are reconstructing back from a YAML file into multiple files.

**Comment by lhein** [comment]
https://issues.redhat.com/browse/FUSETOOLS2-360 tracks this issue now.
