### ISSUE TITLE
Provide full naming for VDB in "DataVirt: Create VDB" command name

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#29]

**Comment by apupier** [comment]
What means VDB? Virtual Database?
[Here](This snapshot is in the form of a Virtual Database definition, or VDB.) I understand Virtual Database definition but it doesn't match the acronyms. So it is only a Virtual DataBase? and in our case we are creating a Virtual Database Definition?, so a VDB definition?

@lhein @rareddy ?

**Comment by rareddy** [comment]
@apupier yes, it is "Virtual Database" a.k.a "VDB". Although it a definition of it we do not call "VDB Definition" it is just VDB.

**Comment by apupier** [comment]
UI naming proposals:
- `DataVirt: Create a VDB (Virtual Database definition)`
- `DataVirt: Create a Virtual Database definition (VDB)`

side note: maybe the prefix should not be `DataVirt` but `Teiid`for all commands?

**Comment by rareddy** [comment]
we should do prefix as just `dv` since we are not using the community name in the naming.

**Comment by lhein** [comment]
see #65
