### ISSUE TITLE
Open "vdb" file after creation

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#30]
to let user edit it.
or emphasize it in "Data Virtualization" view

**Comment by apupier** [comment]
based on https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.d9goxmxbmbt0 , after creation thesql/ddl editor needs to be opened

**Comment by lhein** [comment]
see #68
