### ISSUE TITLE
Check real name for Data Virtualization product

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#37]
in description it is called `Red Hat DataVirt`
on website it is called `Red Hat JBoss Data Virtualization` https://developers.redhat.com/products/datavirt/overview
as display name it is called simply `DataVirt`

**Comment by apupier** [comment]
@rareddy What is the official name that we should use everywhere?

**Comment by rareddy** [comment]
It is NOT either `Red Hat data Virt` not `Red Hat JBoss Data Virtualization`, these are names of the old product, which EOL now.

The new product name will be (for now) `Red Hat Integration - Data Virtualization` or simply `Data Virtualization`. However, here since this plugin is a community plugin, I would start with `Teiid`.

**Comment by apupier** [comment]
what Marketing is currently recommending for VS Code extension for the name is to suffix with "by Red Hat".

Just `Teiid` might not be very clear for users on the purpose of the extension. I'm unable to find what it means.

What about `Teiid - Data Virtualization tooling by Red Hat`?

**Comment by rareddy** [comment]
Can we do 

`Red Hat Integration - Data Virtualization tooling by Red Hat`

**Comment by apupier** [comment]
if we have `Red Hat` mentioned first, I think we can get rid of the `by Red Hat`, so would mean:
`Red Hat Integration - DataVirtualization tooling``

**Comment by rareddy** [comment]
Yep. Either that or simply "Data Virtualization Tooling" (two words)

**Comment by apupier** [comment]
oups my bad, it was a typo for the Data Virtualization in a single word. Thanks for noticing to avoid any confusions
