### ISSUE TITLE
provide more keywords to help searchability

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#39]
currently: "datavirt" and "data"

what about adding:
- Data Virtualization
- Red Hat Data Virtualization ([Red Hat Jboss Data virtualization](https://github.com/jboss-fuse/vscode-datavirt/issues/37)?)
- Data Integration solution (used as first description words [in Red Hat developers page](https://developers.redhat.com/products/datavirt/overview) )

**Comment by lhein** [comment]
Please create a FUSETOOLS2 issue for this.

**Comment by apupier** [comment]
moved to JIRA https://issues.redhat.com/browse/FUSETOOLS2-389
