### ISSUE TITLE
Provide tests to cover functionality of the plugin for usecase 1

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#45]
- create vdb file
- check appears in Tree View
- check validation of OpenShift resource name
- check editor opened with ddl request
- modifiy request
- save/close
- check content of file

**Comment by lhein** [comment]
I am wondering if we should make this the super task and create sub tasks for all missing tests.

**Comment by apupier** [comment]
I'm fine with both approaches
