### ISSUE TITLE
Provided VDB name needs to follow OpenShift resource name convention

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#59]
when creating a new VDB, a validation needs to be performed to follow the OpenShift resource name convention

see https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.d9goxmxbmbt0

**Comment by lhein** [comment]
see https://github.com/jboss-fuse/vscode-datavirt/pull/70
