### ISSUE TITLE
remove ignore-script task

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#6]
https://github.com/jboss-fuse/vscode-datavirt/blob/3c73b7a7410f1d5c6893f75b74d9cd0c613df46f/Jenkinsfile#L20there is no script for this extension so no need to call this extra step

https://github.com/jboss-fuse/vscode-datavirt/blob/3c73b7a7410f1d5c6893f75b74d9cd0c613df46f/.travis.yml#L11

**Comment by lhein** [comment]
fixed
