### ISSUE TITLE
Use Teiid logo

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#63]
instead of generic Red Hat Integration one https://issues.redhat.com/browse/DESIGN-1531

when [legal review has been done](https://issues.redhat.com/browse/DESIGN-1531?focusedCommentId=13963499&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13963499)

**Comment by lhein** [comment]
Please create a FUSETOOLS2 issue for this.

**Comment by apupier** [comment]
moved to JIRA https://issues.redhat.com/browse/FUSETOOLS2-388
