### ISSUE TITLE
Track usage numbers on https://vscode-marketplace-stats.6923.rh-us-east-1.openshiftapps.com/

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#64]
need to contact Fred Bricon after first publication https://vscode-marketplace-stats.6923.rh-us-east-1.openshiftapps.com/

**Comment by lhein** [comment]
Please raise a FUSETOOLS2 jira issue for this.

**Comment by apupier** [comment]
created https://issues.redhat.com/browse/FUSETOOLS2-386
