### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#7]
there are a bunch of unused dependencies in package.json. For easier maintenance and lighter vsix, this list should be restrained to minimal required one

**Comment by lhein** [comment]
which ones are you referring to?

**Comment by apupier** [comment]
for instance:
https://github.com/jboss-fuse/vscode-datavirt/blob/a2548b2037624a053c2e2b9f21229e9b97a66c76/package.json#L169

https://github.com/jboss-fuse/vscode-datavirt/blob/a2548b2037624a053c2e2b9f21229e9b97a66c76/package.json#L175

https://github.com/jboss-fuse/vscode-datavirt/blob/a2548b2037624a053c2e2b9f21229e9b97a66c76/package.json#L163

would need to go through the whole list

**Comment by lhein** [comment]
I agree, those need some cleanup but they don't affect the size of the vsix.

**Comment by lhein** [comment]
I left the extension tester in there as we might need it in near future.
