### ISSUE TITLE
Create Datasource replace SpringBoot

### ISSUE THREAD

**Issue by rareddy** [jboss-fuse/vscode-datavirt#86]
When creating a new data source, remove the option "SpringBoot", the options should be typical relational data sources like Oracle, PostgreSQL, MySQL, DB2 etc. The complete supported list is here https://github.com/teiid/teiid-openshift-examples/blob/master/datasources.adoc#configuring-relational-database

Maybe we need to add another property to capture the TYPE (Oracle vs MySQL) in those properties implicitly.

IMO, we need a different way to capture the values of these properties, the current one does seem intuitive to me, also we should show the values (either in left side panel)  once they were entered and the ability to modify them.

**Comment by rareddy** [comment]
Now this enhancement is finished, will be released into community Operator soon. https://issues.redhat.com/browse/ENTESB-11938?focusedCommentId=13991240&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13991240

**Comment by lhein** [comment]
let us split this issue in 2 tasks
1. remove the spring boot datasource type
2. refactor the whole datasource type to reflect the format changes u did upstream

**Comment by lhein** [comment]
created https://github.com/jboss-fuse/vscode-datavirt/issues/110

**Comment by lhein** [comment]
created https://github.com/jboss-fuse/vscode-datavirt/issues/111

**Comment by lhein** [comment]
I am closing this issue in favor of the 2 created ones.
